
cache:
  paths:
    - .m2/repository/

image:  markhobson/maven-chrome:jdk-11

stages:
  - build
  - test-run

build-project:
  stage: build
  script:
    - echo "Building the project"
    - mvn clean install

run-tests:
  stage: test-run
  script:
    - echo "Executing test run"
    - mvn test

  dependencies:
    - build-project
  artifacts:
    paths:
      - ./target/test-classes/*.*
    when: always
    expire_in: 1 hour
